#!/usr/bin/python3

# Copyright (C) 2012-2017 Cyrille Defranoux
#
# This file is part of Homewatcher.
#
# Homewatcher is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Homewatcher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Homewatcher. If not, see <http://www.gnu.org/licenses/>.
#
# For any question, feature requests or bug reports, feel free to contact me at:
# knx at aminate dot net

import argparse
import re

def readIncludedFileLine(filename):
    with open(filename) as file:
        return ''.join(file.readlines())

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('template', help='Template file that contains the markdown to be modified to include the configuration.', metavar='TMP')
    parser.add_argument('output', help='Output file that is the result of the insertion of the configuration sample into the template.')
    args = parser.parse_args()

    inclusionRegex = re.compile('{{.*}}')

    with open(args.template) as templateFile:
        templateLines = templateFile.readlines()
        with open(args.output, 'w') as outputFile:
            outputFile.write('<!-- Autogenerated file from {0}. DO NOT MODIFY IT!-->\n'.format(args.template))
            for line in templateLines:
                for matchedString in inclusionRegex.findall(line):
                    includeFilename = matchedString[2:-2]
                    line = line.replace(matchedString, readIncludedFileLine(includeFilename), 1)

                outputFile.write(line)
